version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: client/api-gateway-ui/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"

