### Create an Expense
POST http://localhost:8081/gate/expense
Content-Type: application/json

{
  "name": "Lunch",
  "amount": 10.5
}

### Create an Expense
POST http://localhost:8081/gate/expense
Content-Type: application/json

{
  "name": "Lunch",
  "amount": 10.5
}

### Create an Expense
POST http://localhost:8081/gate/expense
Content-Type: application/json

{
  "name": "Lunch",
  "amount": 10.5
}

### Create an Expense
GET http://localhost:8081/gate/jwt/expense
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MzE4Njc5OTMsImlhdCI6MTczMTc4MTU5MywidXNlcklEIjoidXNlciJ9.NUnoPL7CP50X7acvZc0_uvC2jhePb4oayjGOz_5OzNM
### Create an Expense
POST http://localhost:8081/gate/jwt/expense/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MzE4Njc5OTMsImlhdCI6MTczMTc4MTU5MywidXNlcklEIjoidXNlciJ9.NUnoPL7CP50X7acvZc0_uvC2jhePb4oayjGOz_5OzNM
Content-Type: application/json

{
  "name": "Lunch",
  "amount": 10.5
}


### Create an Expense
POST http://localhost:4001/expense
Content-Type: application/json

{
  "name": "Lunch",
  "amount": 10.5
}

### Create an Expense
POST http://localhost:8081/gate/expense
Content-Type: application/json

{
  "name": "Lunch",
  "amount": 10.5
}


### Create an Expense
POST http://localhost:8081/gate/expense
Content-Type: application/json

{
  "name": "Lunch",
  "amount": 10.5
}


### Create an Expense
POST http://localhost:8081/gate/expense/1
Content-Type: application/json

{
  "name": "Lunch",
  "amount": 10.5
}


###

### Get All Expenses
GET http://localhost:8081/gate/expense/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MzE4NjQyMzUsImlhdCI6MTczMTc3NzgzNX0.tfD4kVG3XblHfEnwHVOP47PeqRmyJkOyeLM9Kz_HrNo
###

### Get a Specific Expense
GET http://localhost:8081/gate/expense

###

### Update an Expense
PUT http://localhost:8081/gate/expense/1
Content-Type: application/json

{
  "name": "Dinner",
  "amount": 20.0
}

###

### Delete an Expense
DELETE http://localhost:8081/gate/expense/2
